# Generated by Django 4.0.3 on 2022-04-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.auction'),
        ),
    ]
