# Generated by Django 4.0.3 on 2022-04-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='auctions',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rel_category', to='auctions.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction'),
        ),
    ]
