# Generated by Django 4.0.3 on 2022-04-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='pricebidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_pricebidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
