# Generated by Django 4.0.3 on 2022-04-15 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.TextField(max_length=300)),
                ('commentuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_commentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='rel_comments', to='auctions.comment'),
        ),
    ]
