# Generated by Django 4.0.3 on 2022-04-18 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment_auction_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_watchuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
